DATASET:
    NAME: "datasetAC_distill"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 60
    BATCH_SIZE: 8
    CROP_SIZE: 256
    BASE_SIZE: 256
    SUPERVISE_SIZE: 256
    BACKBONE_PRETRAINED_PATH: "pretrain/resnet50-19c8e357.pth"
    MODEL_PRETRAINED_PATH: "runs/checkpoints/0001_deeplabv3p_resnet50/best_model.pth"
TEST:
    BATCH_SIZE: 4
    SCALES: [0.75, 1.0, 1.25]

DISTILL:
    ALPHA: 10
    TEMPERATURE: 5

SOLVER:
    LR: 0.04
    OPTIMIZER: "SGD"
    USE_FP16: True
    AUX: True
    LOSS_NAME: "distill"

MODEL:
    MODEL_NAME: "DeepLabV3_Plus_V2"
    BACKBONE: "ibn_resnet50"
    OUTPUT_STRIDE: 8

