DATASET:
    NAME: "datasetAC"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 60
    BATCH_SIZE: 8
    CROP_SIZE: 512
    BASE_SIZE: 512
    SUPERVISE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrain/ShuffleNetV2+.Large.pth.tar"
TEST:
    BATCH_SIZE: 8
    TEST_MODEL_PATH: "runs/checkpoints/0013_deeplabv3p_shufflenetv2p/best_model.pth"
    SCALES: [0.75, 1.0, 1.25]

SOLVER:
    LR: 0.04
    OPTIMIZER: "SGD"
    USE_FP16: True
    AUX: True

MODEL:
    MODEL_NAME: "DeepLabV3_Plus_V2"
    BACKBONE: "shufflenetv2_plus"
    OUTPUT_STRIDE: 8

