DATASET:
    NAME: "datasetAC_distill"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 120
    BATCH_SIZE: 32
    CROP_SIZE: 256
    BASE_SIZE: 256
    SUPERVISE_SIZE: 256
    BACKBONE_PRETRAINED_PATH: "pretrain/note10_lat_8ms.pth"
    MODEL_PRETRAINED_PATH: "runs/checkpoints/0028_deeplabv3p_ofanote10/best_model.pth"
TEST:
    BATCH_SIZE: 32
    SCALES: [0.75, 1.0, 1.25]

SOLVER:
    LR: 0.02
    OPTIMIZER: "SGD"
    AUX: True
    LOSS_NAME: "distill"

DISTILL:
    ALPHA: 1
    TEMPERATURE: 1

MODEL:
    MODEL_NAME: "DeepLabV3_Plus_V2"
    BACKBONE: "ofa_note10_lat_8ms"
    OUTPUT_STRIDE: 8

