DATASET:
#    NAME: "datasetAC"
    NAME: "datasetA"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 60
    BATCH_SIZE: 8
    CROP_SIZE: 512
    BASE_SIZE: 512
    SUPERVISE_SIZE: 256
    BACKBONE_PRETRAINED_PATH: "pretrain/resnext101_32x8d-8ba56ff5.pth"

TEST:
    BATCH_SIZE: 16
    TEST_MODEL_PATH: "runs/checkpoints/0039_dunet_resnext101/best_model.pth"
    SCALES: [0.75, 1.0, 1.25]

SOLVER:
    LR: 0.04
    OPTIMIZER: "SGD"
    USE_FP16: True
    AUX: True

MODEL:
    MODEL_NAME: "DUNetV2"
    BACKBONE: "resnext101_32x8d"
    OUTPUT_STRIDE: 8

