DATASET:
    NAME: "datasetAC"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 60
    BATCH_SIZE: 16
    CROP_SIZE: 256
    BASE_SIZE: 256
    SUPERVISE_SIZE: 256
    BACKBONE_PRETRAINED_PATH: "pretrain/v100_gpu64_6ms.pth"
TEST:
    BATCH_SIZE: 32
    SCALES: [0.75, 1.0, 1.25]

SOLVER:
    LR: 0.004
    OPTIMIZER: "SGD"
    AUX: True
    LOSS_NAME: "distillv3"

DISTILL:
    TEACHER_NAME: "DeepLabV3_Plus_V2_Teacher"
    TEACHER_BACKBONE: "resnext50_32x4d"
    TEACHER_PRETRAINED_PATH: "runs/checkpoints/0047_deeplabv3p_resnext50/best_model.pth"
    BASE_SIZE: 256
    ALPHA: 10
    BETA: 0.5
    TEMPERATURE: 1

MODEL:
    MODEL_NAME: "DeepLabV3_Plus_V2_Student"
    BACKBONE: "ofa_v100_gpu64_6ms"
    OUTPUT_STRIDE: 8

