DATASET:
    NAME: "datasetAC"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 120
    BATCH_SIZE: 32
    CROP_SIZE: 256
    BASE_SIZE: 256
    SUPERVISE_SIZE: 256
    BACKBONE_PRETRAINED_PATH: "pretrain/resnext101_32x8d-8ba56ff5.pth"
TEST:
    BATCH_SIZE: 32
    SCALES: [0.75, 1.0, 1.25]

SOLVER:
    LR: 0.08
    OPTIMIZER: "SGD"
    USE_FP16: True
    AUX: True

MODEL:
    MODEL_NAME: "DUNetV2Nearest"
    BACKBONE: "resnext101_32x8d"
    OUTPUT_STRIDE: 8

